---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rust:1.54
    commands:
      - cargo test
  - name: build
    image: rust:1.54
    commands:
      - cargo build
